### ISSUE TITLE
Errors on startup

### ISSUE THREAD

**Issue by jrappen** [SublimeText/TrailingSpaces#117]
```text
Traceback (most recent call last):
  File "..\sublime3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "..\sublime3\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 416, in on_selection_modified
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 129, in match_trailing_spaces
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 86, in find_trailing_spaces
  File "..\sublime3\sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
```

```text
Traceback (most recent call last):
  File "..\sublime3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "..\sublime3\sublime_plugin.py", line 488, in <lambda>
    run_callback('on_modified', callback, lambda: callback.on_modified(v))
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 408, in on_modified
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 129, in match_trailing_spaces
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 86, in find_trailing_spaces
  File "..\sublime3\sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
```

```text
Traceback (most recent call last):
  File "..\sublime3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "..\sublime3\sublime_plugin.py", line 505, in <lambda>
    run_callback('on_selection_modified', callback, lambda: callback.on_selection_modified(v))
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 416, in on_selection_modified
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 129, in match_trailing_spaces
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 86, in find_trailing_spaces
  File "..\sublime3\sublime.py", line 641, in __getitem__
    raise IndexError()
IndexError
```

```text
Traceback (most recent call last):
  File "..\sublime3\sublime_plugin.py", line 389, in run_callback
    expr()
  File "..\sublime3\sublime_plugin.py", line 522, in <lambda>
    run_callback('on_activated', callback, lambda: callback.on_activated(v))
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 419, in on_activated
  File "trailing_spaces in ..\sublime3\Data\Installed Packages\TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./python3.3/codecs.py", line 896, in open
```

---

* `Win10 Pro (x64) 1703`
* Sublime Text `Build 3131` x64 portable
* TrailingSpaces `2016.09.26.08.04.19`

**Comment by jrappen** [comment]
closing as stale
