### ISSUE TITLE
Broken in ST2

### ISSUE THREAD

**Issue by cmer** [SublimeText/TrailingSpaces#41]
```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 200, in on_selection_modified
  File "./sublime_plugin.py", line 154, in run_timed_function
  File "./sublime_plugin.py", line 199, in <lambda>
  File "./trailing_spaces.py", line 392, in on_selection_modified
  File "./trailing_spaces.py", line 123, in match_trailing_spaces
  File "./trailing_spaces.py", line 90, in find_trailing_spaces
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Writing file /Users/carl/Code/spec/controllers/categories_controller_spec.rb with encoding UTF-8
```

**Comment by rchl** [comment]
Deemed not worth handling for ST2's sake.
