### ISSUE TITLE
Need to wrap codecs.open in try/catch in freeze_last_version

### ISSUE THREAD

**Issue by bvm42** [SublimeText/TrailingSpaces#57]
I find my console littered with things like this:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 303, in on_activated
    callback.on_activated(v)
  File "trailing_spaces in C:\Users\Bill\AppData\Roaming\Sublime Text 3\Installed Packages\TrailingSpaces.sublime-package", line 395, in on_activated
  File "trailing_spaces in C:\Users\Bill\AppData\Roaming\Sublime Text 3\Installed Packages\TrailingSpaces.sublime-package", line 416, in freeze_last_version
  File "X/codecs.py", line 884, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Bill\\AppData\\Local\\Temp\\$$_49F1\\Default (Windows).sublime-mousemap'
```

which seems to happen whenever I delete/rename a file that is open in ST3.  Not fatal or anything, but it's a distraction in the console.

**Comment by Pictor13** [comment]
Made a pull request (#126 ) for it. Hope it will be merged, I can't see this repository being updated since a while; even if the author is actually quite active on Github.
Maybe he disabled notifications from this repo?

**Comment by rchl** [comment]
This case should be covered already. See https://github.com/SublimeText/TrailingSpaces/pull/126 for explanation.
