### ISSUE TITLE
on_pre_save fails for new files

### ISSUE THREAD

**Issue by Kronuz** [SublimeText/TrailingSpaces#62]
For **new** files being saved, `freeze_last_version` called from `on_pre_save` tries to open a file that is about to be created (but it's not yet there). So the `open()` fails with `FileNotFoundError`.

**Comment by cardonator** [comment]
I know this is a really old issue, but this is still happening on v2015.10.27 in ST3

Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 240, in on_pre_save
    callback.on_pre_save(v)
  File "trailing_spaces in /home/bcardon/.config/sublime-text-3/Installed Packages/TrailingSpaces.sublime-package", line 424, in on_pre_save
  File "trailing_spaces in /home/bcardon/.config/sublime-text-3/Installed Packages/TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./codecs.py", line 885, in open
FileNotFoundError: [Errno 2] No such file or directory: '/home/bcardon/.config/sublime-text-3/Packages/User/Default (Linux).sublime-keymap'

**Comment by Pictor13** [comment]
I made a pull request (#126 ). Cross fingers that @jbrooksuk will see this and merge it! 🤞

**Comment by rchl** [comment]
There is a `os.path.isfile` check in the code now so this should be fixed.
