### ISSUE TITLE
Settings Being Overwritten?

### ISSUE THREAD

**Issue by matthewwithanm** [SublimeText/TrailingSpaces#65]
I'm not sure if this is an issue with TrailingSpaces or ST3, but it's only happened with this bundle so I'm posting here.

For some reason, my settings keep being overwritten. I edit my user-specific package settings to look like this:

``` json
{
    "trailing_spaces_highlight_color": "trailingspaces.invalid"
}
```

Then a few days later I notice that it's not highlighting anymore, so I open the file and see this:

``` json
{
    "trailing_spaces_highlight_color": ""
}
```

This has happened several times now, and only for TrailingSpaces. Any idea what could be up?

**Comment by jrdmcgr** [comment]
I ran into this same problem. I was getting this stacktrace in the console.

```
Traceback (most recent call last):
  File "/Users/jmcguire/Desktop/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "trailing_spaces in /Users/jmcguire/Library/Application Support/Sublime Text 3/Installed Packages/TrailingSpaces.sublime-package", line 419, in on_activated
  File "trailing_spaces in /Users/jmcguire/Library/Application Support/Sublime Text 3/Installed Packages/TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./codecs.py", line 885, in open
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jmcguire/Library/Application Support/Sublime Text 3/Packages/TrailingSpaces/trailing_spaces.sublime-settings'
```

I used the command `PackageControl: Advanced Install Package` and types in the package name `TrailingSpaces` and it fixed the problem with my settings.

**Comment by junkystu** [comment]
Same issue here on Linux. I update my user settings file to set `"trailing_spaces_highlight_color": "invalid"` and after saving it, if I edit a file and add some trailing space, the setting is lost and changes back to `"trailing_spaces_highlight_color": ""`

    FileNotFoundError: [Errno 2] No such file or directory: '/home/junkystu/.config/sublime-text-3/Packages/TrailingSpaces/trailing_spaces.sublime-settings'
    reloading settings Packages/User/trailing_spaces.sublime-settings
    reloading /home/junkystu/.config/sublime-text-3/Packages/User/trailing_spaces.sublime-settings
    reloading settings Packages/User/trailing_spaces.sublime-settings

**Comment by panczarny** [comment]
I'm working on ST3 build 3126. After updating I'm facing the same issue.

**Comment by theluk** [comment]
this is driving me nuts...
