### ISSUE TITLE
Errors upon launch

### ISSUE THREAD

**Issue by ghost** [SublimeText/TrailingSpaces#85]
``` python
Traceback (most recent call last):
  File "C:\Users\________\Sublime Text\sublime_plugin.py", line 240, in on_pre_save
    callback.on_pre_save(v)
  File "trailing_spaces in C:\Users\________\Sublime Text\Data\Installed Packages\TrailingSpaces.sublime-package", line 424, in on_pre_save
  File "trailing_spaces in C:\Users\________\Sublime Text\Data\Installed Packages\TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./codecs.py", line 885, in open
```

**Comment by rchl** [comment]
Duplicate of #62
