### ISSUE TITLE
issue in windows 7 portable sublime 3 build 3083 on_activated freeze_last_version

### ISSUE THREAD

**Issue by tbaker4802** [SublimeText/TrailingSpaces#95]
I looked but I don't see this issue posted anywhere. Here it is!

I get this error anytime I'm saving a file.

Maybe it's related to the file versioning preference? (    "atomic_save": true, )

Not sure, I played around with it some but it's not causing me too many issues I mainly use this for the white-space highlighting not removing at save. 

Anyways.

setting             "trim_automatic_white_space": true
to             "trim_automatic_white_space": false

fixes the problem for me... but I'd like to use it. 

Thanks

Here's an example error:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\myuser\Desktop\sublime\sublime 3\Data\Packages\Default\Default (Windows).sublime-keymap'
Traceback (most recent call last):
  File "C:\Users\myuser\Desktop\sublime\sublime 3\sublime_plugin.py", line 304, in on_activated
    callback.on_activated(v)
  File "trailing_spaces in C:\Users\myuser\Desktop\sublime\sublime 3\Data\Installed Packages\TrailingSpaces.sublime-package", line 419, in on_activated
  File "trailing_spaces in C:\Users\myuser\Desktop\sublime\sublime 3\Data\Installed Packages\TrailingSpaces.sublime-package", line 440, in freeze_last_version
  File "./codecs.py", line 885, in open

**Comment by rchl** [comment]
`atomic_save` is not supported anymore, I believe.
And this bug report doesn't have enough information to go with (It looks like it's missing crucial error triggered from codecs.py).
